apiVersion: batch/v1
kind: CronJob
metadata:
  name: xfusion
spec:
  schedule: "*/10 * * * *"  # Runs every 10 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-xfusion  # Container name
            image: nginx:latest # Using the latest nginx image
            command: 
            - /bin/sh
            - -c
            - echo Welcome to xfusioncorp! # Dummy command
          restartPolicy: OnFailure  # Restart policy